exclude:
  - .vscode/
  - data/
  - templates/
  - .gitignore
  - .prettierrc
  - build-character-guide-pages.js
  - build-character-guide-pages-pug.js
  - package.json
  - package-lock.json
  - tsconfig.json
